[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"

[publish.categories]
v-rising = ["oakveil-update", "mods", "client"]

[package]
namespace = "zfolmt"
name = "RetroCamera"
versionNumber = "1.4.4"
description = "Streamlined camera enhancements w/ additional features!"
websiteUrl = "https://github.com/mfoltz/RetroCamera"
containsNsfwContent = false
